name: Bug report
description: Report a crash or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: textarea
    id: summary
    attributes:
      label: Brief summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
    validations:
      required: true
  - type: input
    id: kosen-version
    attributes:
          label: Kosen version
          description: You can find your Kosen version in **Settings → About**.
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android version
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
    validations:
      required: true
